# Create env: conda env create -f environment.yml
name: yala-env
dependencies:
  - python==3.7
  - pytest==5.2.2
  - scikit-learn==0.21.3
  - ipython
  - pip
  - pip:
    - pandas==0.25.2
    - numpy==1.17.4
    - scipy==1.3.2
    - networkx==2.4
    - matplotlib==3.1.1
    - dill==0.3.1.1
    - xgboost==0.90